version: '2'
services:
  dns:
    restart: always
    # host network mode is required to be able receive DHCPOFFER on physical machines outside of docker
    network_mode: host
    image: strm/dnsmasq
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    # Publishing of ports is not required when runing in host network mode
    # ports:
      # - "53:53/udp"
      # - "67:67/udp"
    cap_add:
      - NET_ADMIN
    entrypoint: ["dnsmasq", "-k"]
