version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: postgres13:5432
      WORDPRESS_DB_USER: postgres
      WORDPRESS_DB_PASSWORD: posgres
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress-data:/var/www/html
    networks:
      - databases

networks:
  databases:
    external:
      name: databases

