version: "2.1"
services:
  dhcp:
    restart: always
    # host network mode is required to be able receive DHCPOFFER on physical machines outside of docker
    network_mode: host
    build: ./dnsmasq
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    # Publishing of ports is not required when runing in host network mode
    # ports:
      # - "53:53/udp"
      # - "67:67/udp"
    cap_add:
      - NET_ADMIN
    entrypoint: ["dnsmasq", "-k"]
  netbootxyz:
    image: ghcr.io/linuxserver/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      # - MENU_VERSION=2.0.28 #optional
    volumes:
      - /opt/netboot/config:/config
      - /opt/tmp/netboot/assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped
