version: "3.8"

services:
  unifi:
    image: jacobalberty/unifi:v8.5
    container_name: unifi-controller
    restart: unless-stopped
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./unifi_data:/unifi  # Persist data in a local folder
    ports:
      - "3478:3478/udp"       # STUN
      - "10001:10001/udp"     # AP discovery
      - "8080:8080"           # Device/ controller communication
      - "8443:8443"           # Controller UI / API
      - "8843:8843"           # HTTPS portal redirect
      - "8880:8880"           # HTTP portal redirect
      - "6789:6789"           # Speed test
      - "1900:1900/udp"       # UDP for UPnP
      - "5514:5514/udp"       # Remote syslog

    networks:
      - unifi_network

networks:
  unifi_network:
    driver: bridge
